# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar curl y otras dependencias necesarias
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copiar los archivos de la aplicación Flask al contenedor
COPY . /app

# Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Descargar el script wait-for-it.sh y darle permisos de ejecución
RUN curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

# Exponer el puerto en el que Flask escuchará
EXPOSE 8080

# Comando para iniciar la aplicación Flask
CMD ["./wait-for-it.sh", "mysql:3306", "--", "python", "app.py"]
